object Libs {
    const val activityCompose = "androidx.activity:activity-compose:1.3.1"
    const val assertJCore = "org.assertj:assertj-core:3.20.2"
    const val composeMaterial = "androidx.compose.material:material:${Versions.compose}"
    const val composeUi = "androidx.compose.ui:ui:${Versions.compose}"
    const val composeUiTestJUnit4 = "androidx.compose.ui:ui-test-junit4:${Versions.compose}"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling:${Versions.compose}"
    const val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview:${Versions.compose}"
    const val coreKtx = "androidx.core:core-ktx:1.5.0"
    const val googleZxingCore = "com.google.zxing:core:3.4.1"
    const val jUnit5Api = "org.junit.jupiter:junit-jupiter-api:5.7.1"
    const val jUnit5Engine = "org.junit.jupiter:junit-jupiter-engine:5.7.1"
    const val jUnit5Vintage = "org.junit.vintage:junit-vintage-engine:5.7.1" // for jUnit4 tests
    const val koinAndroid = "io.insert-koin:koin-android:${Versions.koin}"
    const val koinAndroidCompose = "io.insert-koin:koin-androidx-compose:${Versions.koin}"
    const val kotlinxCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2"
    const val kotlinxCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2"
    const val kotlinxCoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
    const val lifecycleViewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.4.0"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
    const val mockk = "io.mockk:mockk:1.12.0"
    const val testEspressoCore = "androidx.test.espresso:espresso-core:3.4.0"
    const val testExtJUnit = "androidx.test.ext:junit:1.1.3"
    const val tinyLogApi = "org.tinylog:tinylog-api-kotlin:2.2.1"
    const val tinyLogImpl = "org.tinylog:tinylog-impl:2.2.1"
}
